### ISSUE TITLE
error at server start up

### ISSUE THREAD

**Issue by sonezu** [Rexios80/Health-Data-Server-Overlay#33]
**Did you try [these troubleshooting steps?](https://github.com/Rexios80/Health-Data-Server-Overlay/wiki/Troubleshooting)**
Yes

**Hardware/Software**
- iPhone: X
- iOS: 14.0.2
- Apple Watch: Serie 6 44mm
- watchOS: 4.0.2
- Windows: Windows 10 Home 1909
- App: unknown
- Server: unknown

**To Reproduce**
I've downloaded the Github-Folder and the Windows executable into the same folder.
Upon executing the HDS-Overlay-win.exe it shows the following lines:

Error: listen EACCES: permission denied 0.0.0.0:8080
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at Function.listen (C:\snapshot\apple-watch-health-data-server\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (C:\snapshot\apple-watch-health-data-server\public\app.js:73:18)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)
    at Module.load (internal/modules/cjs/loader.js:1047:32)
    at Function.Module._load (internal/modules/cjs/loader.js:935:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12) {
  code: 'EACCES',
  errno: -4092,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 8080
}
The application has crashed. If you need help, please create an issue on the GitHub page.

**Expected behavior**
Startup server to connect the Watch-app to

**Additional context**
node-version is v12.19.0

**Comment by Rexios80** [comment]
You only need the executable not the source code.
Are you running another server on port 8080? It's weird that you're getting an EACCESS error instead of an EADDRINUSE error. Do you have a custom firewall setup?

**Comment by Rexios80** [comment]
https://github.com/Rexios80/Health-Data-Server-Overlay#configuration

**Comment by sonezu** [comment]
Thank you, I was just extremely dumb and got the config filename wrong. Everything works great now. Thank you!
