### ISSUE TITLE
Doenst show numbers

### ISSUE THREAD

**Issue by kingrun** [Rexios80/Health-Data-Server-Overlay#7]
So I purchased the app. Downloaded Git and node.js installed everything. when launching it throws this error message though it seems in regarding with Discord which I dont need at the moment. The localhost:8080 starts and I can connect to it locally it just shows - lines where the numbers should be next to the icons. My apple watch is set to the ip-address:8080 it shows the time calories and heart rate it is currently sending but nothing seems to be coming through to the PC. I added a port forward to 8080 on my pc I disabled my firewall to test it out nothing seems to help.
The error when launching is :

Listening at port 8080
(node:14784) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.onerror (C:\Users\King\Desktop\Health-Data-Server-Overlay-3.0\node_modules\discord-rpc\src\transports\ipc.js:32:16)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14784) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14784) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

How do I troubleshoot?

**Comment by kingrun** [comment]
Problem found after troubleshooting router. Seems port did not open correctly
